spring:
  application:
    name: demo1

  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: 0000
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # ?????? ??? ?? ????
    show-sql: true # ??? SQL ?? ??
    properties:
      hibernate:
        format_sql: true # SQL ????? ??

  transaction:
    management:
      enabled: true # ???? ?? ???

server:
  port: 8080 # ?????? ?? ??

logging:
  level:
    org:
      springframework: INFO # ??? ????? ?? ??
      hibernate: DEBUG # ?????? ?? ??
